import { Download } from 'lucide-react';
import type { AnalysisResult } from '@/lib/resumeAnalyzer';

interface ExportPDFProps {
  result: AnalysisResult;
  resumeName: string;
}

export function ExportPDF({ result, resumeName }: ExportPDFProps) {
  const handleExport = () => {
    // Build a printable HTML document and trigger print-to-PDF
    const content = `
<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Resume Analysis Report</title>
<style>
body { font-family: 'Segoe UI', Arial, sans-serif; padding: 40px; color: #1a1a2e; max-width: 800px; margin: 0 auto; }
h1 { color: #16a34a; border-bottom: 2px solid #16a34a; padding-bottom: 8px; }
h2 { color: #0ea5e9; margin-top: 24px; }
.score-box { background: #f0fdf4; border: 2px solid #16a34a; border-radius: 12px; padding: 20px; text-align: center; margin: 20px 0; }
.score-box .score { font-size: 48px; font-weight: bold; color: #16a34a; }
.breakdown { display: flex; gap: 20px; margin: 12px 0; }
.breakdown div { flex: 1; background: #f8fafc; border-radius: 8px; padding: 12px; text-align: center; }
.skill-tag { display: inline-block; padding: 4px 10px; margin: 3px; border-radius: 20px; font-size: 12px; }
.matched { background: #dcfce7; color: #166534; }
.missing { background: #fee2e2; color: #991b1b; }
.suggestion { padding: 8px 0; border-bottom: 1px solid #e5e7eb; }
.footer { margin-top: 40px; text-align: center; color: #9ca3af; font-size: 12px; }
</style></head><body>
<h1>Resume Analysis Report</h1>
<p><strong>Resume:</strong> ${resumeName}</p>
<p><strong>Date:</strong> ${new Date().toLocaleDateString()}</p>

<div class="score-box">
  <div class="score">${result.matchScore}%</div>
  <div>${result.mode === 'match' ? 'Job Match Score' : 'Resume Quality Score'}</div>
</div>

${result.mode === 'match' ? `<div class="breakdown">
  <div><strong>${result.tfidfScore}%</strong><br/>TF-IDF Similarity (40%)</div>
  <div><strong>${result.skillScore}%</strong><br/>Skill Match (60%)</div>
</div>` : `<h2>Detected Sections</h2>
<div>${result.detectedSections.map(s => `<span class="skill-tag matched">${s}</span>`).join('')}</div>
<p>Action Verbs Found: <strong>${result.actionVerbCount}</strong> | Keyword Strength: <strong>${result.keywordStrength}%</strong></p>`}

<h2>${result.mode === 'match' ? 'Matched Skills' : 'Skills Detected'} (${result.matchedKeywords.length})</h2>
<div>${result.matchedKeywords.map(s => `<span class="skill-tag matched">${s}</span>`).join('')}</div>

${result.mode === 'match' && result.missingSkills.length > 0 ? `<h2>Missing Skills (${result.missingSkills.length})</h2>
<div>${result.missingSkills.map(s => `<span class="skill-tag missing">${s}</span>`).join('')}</div>` : ''}

${result.suggestions.length > 0 ? `
<h2>Suggestions</h2>
${result.suggestions.map((s, i) => `<div class="suggestion"><strong>${i + 1}.</strong> ${s}</div>`).join('')}
` : ''}

<div class="footer">Generated by ResumeIQ — Built by Vommi Uma Mahesh</div>
</body></html>`;

    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(content);
      printWindow.document.close();
      printWindow.onload = () => {
        printWindow.print();
      };
    }
  };

  return (
    <button
      onClick={handleExport}
      className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-accent text-accent-foreground font-medium text-sm hover:brightness-110 transition-all"
    >
      <Download className="h-4 w-4" /> Export PDF Report
    </button>
  );
}